# Generated by Django 3.0.3 on 2020-03-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
