# Generated by Django 3.0.3 on 2020-03-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=4)),
                ('room_type', models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('superdelux', 'Superdelux')], max_length=10)),
                ('building_no', models.CharField(max_length=2)),
                ('rector_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=10)),
                ('email_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
