# Generated by Django 3.0.3 on 2020-03-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0002_hostel_student_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
