# Generated by Django 3.0.3 on 2020-03-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0005_student_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_details',
        ),
    ]
