# Generated by Django 3.0.3 on 2020-03-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0007_student_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='hostel_rooms',
            fields=[
                ('room_no', models.IntegerField(primary_key=True, serialize=False)),
                ('person1', models.CharField(max_length=30)),
                ('person2', models.CharField(max_length=30)),
                ('person3', models.CharField(max_length=30)),
                ('room_type', models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('superdelux', 'Superdelux')], max_length=10)),
                ('building_no', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='building_no',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='rector_name',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='room_type',
        ),
    ]
