# Generated by Django 3.0.3 on 2020-03-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0008_auto_20200326_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_rooms',
            name='building_no',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
