# Generated by Django 3.0.3 on 2020-04-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0009_auto_20200329_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='mess_timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=10)),
                ('Monday', models.CharField(max_length=100)),
                ('Tuesday', models.CharField(max_length=100)),
                ('Wednesday', models.CharField(max_length=100)),
                ('Thursday', models.CharField(max_length=100)),
                ('Friday', models.CharField(max_length=100)),
                ('Saturday', models.CharField(max_length=100)),
                ('Sunday', models.CharField(max_length=100)),
            ],
        ),
    ]
