# Generated by Django 3.0.3 on 2020-05-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0010_mess_timetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hostel',
        ),
        migrations.DeleteModel(
            name='mess_timetable',
        ),
    ]
